#requires -Version 7.4

# Task-aware encrypted backup/restore acceptance.
#
# This runner creates strictly named, run-scoped databases on the existing
# Docker Compose PostgreSQL server, seeds the employee journey through the real
# HTTP API, exercises the real encrypted backup and isolated restore scripts,
# compares source and restored evidence, verifies revocation/fencing, rejects a
# tampered backup, writes a sanitized report and removes every resource it
# created. The normal StoreOS database is never read, written, restored into or
# dropped; its name is only checked for existence after cleanup.
[CmdletBinding()]
param(
    [string] $DartPath = 'dart',
    [switch] $SkipPackageResolution,
    [string] $DockerPath = 'docker',
    [ValidateSet('none', 'prepare', 'backup', 'restore', 'verify', 'corruption')]
    # Test hook: abort after the named step to prove failure-path cleanup.
    [string] $InjectFailureAfter = 'none'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Assert-BackupAcceptanceReport.ps1')

$repository = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$serverDirectory = Join-Path $repository 'apps/server'
$composeFile = Join-Path $repository 'compose.yaml'
$runId = [guid]::NewGuid().ToString('N').Substring(0, 16).ToLowerInvariant()
$sourceDatabase = "storeos_backup_accept_$runId"
$restoreDatabase = "storeos_restore_bkacc_$runId"
$corruptDatabase = "storeos_restore_bkacc_${runId}c"
$ownedDatabaseNames = @($sourceDatabase, $restoreDatabase, $corruptDatabase)
$runDirectory = Join-Path $repository ".local/backup-acceptance/$runId"
$manifestPath = Join-Path $runDirectory 'fixture.json'
$resultPath = Join-Path $runDirectory 'verify-result.json'
$reportPath = Join-Path $runDirectory 'report.json'
$apiPort = 8097

$previousEnvironment = @{}
foreach ($name in @(
        'STOREOS_BACKUP_MODE', 'STOREOS_BACKUP_MANIFEST', 'STOREOS_BACKUP_RESULT',
        'STOREOS_BACKUP_SOURCE_DATABASE', 'STOREOS_BACKUP_TARGET_DATABASE',
        'STOREOS_BACKUP_DB_HOST', 'STOREOS_BACKUP_DB_PORT', 'STOREOS_BACKUP_DB_USER',
        'STOREOS_BACKUP_OWNER_PASSWORD_FILE', 'STOREOS_BACKUP_API_PORT')) {
    $previousEnvironment[$name] = [Environment]::GetEnvironmentVariable($name, 'Process')
}

function Import-LocalConfiguration {
    $config = Join-Path $repository '.env'
    if (!(Test-Path -LiteralPath $config -PathType Leaf)) { return }
    foreach ($line in Get-Content -LiteralPath $config) {
        if ($line -match '^\s*(#|$)') { continue }
        if ($line -notmatch '^(STOREOS_[A-Z0-9_]+)=(.*)$') { throw 'Invalid .env line. Use KEY=value without shell expansion.' }
        $name = $Matches[1]
        $value = $Matches[2]
        if ($name.EndsWith('_FILE') -and ![IO.Path]::IsPathRooted($value)) {
            $value = Join-Path $repository $value
        }
        if (![Environment]::GetEnvironmentVariable($name, 'Process')) {
            [Environment]::SetEnvironmentVariable($name, $value, 'Process')
        }
    }
}

function Require-Tool([string]$Name) {
    $command = Get-Command $Name -ErrorAction SilentlyContinue
    if (!$command) { throw "Required tool missing: $Name" }
    return $command.Source
}

function Resolve-SecretFile([string]$Path, [string]$Label) {
    if ([string]::IsNullOrWhiteSpace($Path) -or !(Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Label is missing. Configure the existing StoreOS secrets first."
    }
    return (Resolve-Path -LiteralPath $Path).Path
}

function Test-LoopbackPort([int]$Port) {
    $socket = [Net.Sockets.TcpClient]::new()
    try {
        $socket.Connect('127.0.0.1', $Port)
        return $socket.Connected
    } catch [Net.Sockets.SocketException] {
        return $false
    } finally {
        $socket.Dispose()
    }
}

function Invoke-ComposeDb([string[]]$Arguments) {
    & $dockerTool compose -f $composeFile exec -T db @Arguments | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'The Compose PostgreSQL service rejected the command.' }
}

function Test-AcceptanceDatabaseExists([string]$Name) {
    if ($Name -cnotmatch '^[a-z0-9_]{1,63}$') { throw 'Invalid database name.' }
    $result = & $dockerTool compose -f $composeFile exec -T db sh -ec 'exec psql -U "$POSTGRES_USER" -d postgres -v ON_ERROR_STOP=1 -Atc "$1"' sh "SELECT 1 FROM pg_database WHERE datname='$Name'"
    if ($LASTEXITCODE -ne 0) { throw 'Could not inspect the Compose PostgreSQL server.' }
    return (($result | Where-Object { $_ }) -contains '1')
}

# Destructive cleanup fails closed: only names generated by this run and
# matching the strict acceptance patterns may be dropped.
function Remove-AcceptanceDatabase([string]$Name, [string[]]$AllowedNames) {
    if ($AllowedNames -cnotcontains $Name) { throw 'Refusing to drop a database that does not belong to this run.' }
    if ($Name -cnotmatch '^storeos_(backup_accept|restore)_[a-z0-9_]{1,47}$') { throw 'Refusing to drop an invalid acceptance database name.' }
    if (!(Test-AcceptanceDatabaseExists $Name)) { return 'absent' }
    Invoke-ComposeDb @('sh', '-ec', 'exec psql -U "$POSTGRES_USER" -d postgres -v ON_ERROR_STOP=1 -c "DROP DATABASE \"$1\""', 'sh', $Name)
    if (Test-AcceptanceDatabaseExists $Name) { throw "Acceptance database remains after drop: $Name" }
    return 'removed'
}

function New-AcceptanceSourceDatabase([string]$Name) {
    if ($ownedDatabaseNames -cnotcontains $Name) { throw 'Refusing to create an unowned acceptance database.' }
    Invoke-ComposeDb @(
        'sh', '-ec',
        'createdb -U "$POSTGRES_USER" "$1" && exec psql -U "$POSTGRES_USER" -d postgres -v ON_ERROR_STOP=1 -c "GRANT CONNECT ON DATABASE \"$1\" TO \"$2\""',
        'sh', $Name, $runtimeUser)
}

function Invoke-Fixture([string]$Mode, [int]$TimeoutSeconds = 300) {
    $env:STOREOS_BACKUP_MODE = $Mode
    $options = @{
        FilePath               = $dartTool
        ArgumentList           = @('run', 'tool/backup_restore_fixture.dart')
        WorkingDirectory       = $serverDirectory
        RedirectStandardOutput = (Join-Path $runDirectory "fixture-$Mode.stdout.log")
        RedirectStandardError  = (Join-Path $runDirectory "fixture-$Mode.stderr.log")
        PassThru               = $true
    }
    if ($IsWindows) { $options.WindowStyle = 'Hidden' }
    $process = Start-Process @options
    if (!$process.WaitForExit($TimeoutSeconds * 1000)) {
        $process.Kill($true)
        $process.WaitForExit()
        throw "Fixture $Mode exceeded the timeout."
    }
    if ($process.ExitCode -ne 0) {
        throw "Fixture $Mode failed (exit $($process.ExitCode))."
    }
}

function Write-FixtureFailureDiagnostics {
    foreach ($name in @('fixture-prepare', 'fixture-verify')) {
        foreach ($stream in @('stdout', 'stderr')) {
            $file = Join-Path $runDirectory "$name.$stream.log"
            if (!(Test-Path -LiteralPath $file -PathType Leaf)) { continue }
            Write-Warning "Acceptance diagnostics: $name.$stream.log"
            foreach ($line in (Get-Content -LiteralPath $file | Select-Object -Last 20)) {
                $masked = $line
                foreach ($secret in $sensitiveValues) {
                    foreach ($representation in @($secret, [Uri]::EscapeDataString($secret), [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($secret)))) {
                        if ($representation) { $masked = $masked.Replace($representation, '[REDACTED]') }
                    }
                }
                $masked = $masked -replace '(?i)Bearer\s+[A-Za-z0-9._~+/=-]+', 'Bearer [REDACTED]'
                $masked = $masked -replace '(?i)postgres(?:ql)?://[^\s"<>]+', '[REDACTED_DATABASE_URL]'
                Write-Warning "Acceptance | $masked"
            }
        }
    }
}

$dartTool = $null
$dockerTool = $null
$runtimeUser = 'storeos'
$operatingDatabase = 'storeos'
$failure = $null
$cleanupFailure = $null
$failedStep = 'setup'
$startedAtUtc = [DateTime]::UtcNow.ToString('o')
$steps = [ordered]@{}
$cleanup = [ordered]@{}
$verify = $null
$corruptRejected = $false
$corruptTargetRemoved = $false
$sensitiveValues = [Collections.Generic.List[string]]::new()
$runVerified = $false

try {
    Import-LocalConfiguration
    $dockerTool = Require-Tool $DockerPath
    $dartTool = Require-Tool $DartPath

    $databaseHost = if ([string]::IsNullOrWhiteSpace($env:STOREOS_DB_HOST)) { '127.0.0.1' } else { $env:STOREOS_DB_HOST }
    if ($databaseHost -notin @('127.0.0.1', 'localhost', '::1')) {
        throw 'The acceptance runs only against the loopback Compose database.'
    }
    $databasePort = if ([string]::IsNullOrWhiteSpace($env:STOREOS_DB_PORT)) { 5432 } else { [int]$env:STOREOS_DB_PORT }
    if ($databasePort -lt 1 -or $databasePort -gt 65535) { throw 'STOREOS_DB_PORT is invalid.' }
    if (![string]::IsNullOrWhiteSpace($env:STOREOS_DB_USER)) { $runtimeUser = $env:STOREOS_DB_USER }
    if ($runtimeUser -cnotmatch '^[a-z_][a-z0-9_]{0,62}$') { throw 'STOREOS_DB_USER is not a valid role name.' }
    if (![string]::IsNullOrWhiteSpace($env:STOREOS_DB_NAME)) { $operatingDatabase = $env:STOREOS_DB_NAME }
    if ($operatingDatabase -cnotmatch '^[a-z0-9_]{1,63}$') { throw 'STOREOS_DB_NAME is not a valid database name.' }

    $ownerUser = if (![string]::IsNullOrWhiteSpace($env:STOREOS_DB_MIGRATION_USER)) { $env:STOREOS_DB_MIGRATION_USER } else { 'storeos_owner' }
    if ($ownerUser -cnotmatch '^[a-z_][a-z0-9_]{0,62}$') { throw 'STOREOS_DB_MIGRATION_USER is not a valid role name.' }
    $ownerPasswordFile = if (![string]::IsNullOrWhiteSpace($env:STOREOS_BACKUP_OWNER_PASSWORD_FILE)) { $env:STOREOS_BACKUP_OWNER_PASSWORD_FILE } else { $env:STOREOS_DB_MIGRATION_PASSWORD_FILE }
    if ([string]::IsNullOrWhiteSpace($ownerPasswordFile)) { $ownerPasswordFile = Join-Path $repository '.local/secrets/db_owner_password.txt' }
    $ownerPasswordFile = Resolve-SecretFile $ownerPasswordFile 'The database owner password file'
    $runtimePasswordFile = if (![string]::IsNullOrWhiteSpace($env:STOREOS_DB_PASSWORD_FILE)) { $env:STOREOS_DB_PASSWORD_FILE } else { Join-Path $repository '.local/secrets/db_password.txt' }
    $runtimePasswordFile = Resolve-SecretFile $runtimePasswordFile 'The runtime password file'
    if ($ownerPasswordFile -eq $runtimePasswordFile) { throw 'Owner and runtime password files must differ.' }
    $sensitiveValues.Add([IO.File]::ReadAllText($ownerPasswordFile).Trim())
    $sensitiveValues.Add([IO.File]::ReadAllText($runtimePasswordFile).Trim())
    if (![string]::IsNullOrWhiteSpace($env:STOREOS_TEST_DATABASE)) { $sensitiveValues.Add($env:STOREOS_TEST_DATABASE) }
    if ($sourceDatabase -cnotmatch '^storeos_backup_accept_[a-f0-9]{16}$') { throw 'Generated source database name is invalid.' }
    if ($restoreDatabase -cnotmatch '^storeos_restore_bkacc_[a-f0-9]{16}$') { throw 'Generated restore database name is invalid.' }
    if ($corruptDatabase -cnotmatch '^storeos_restore_bkacc_[a-f0-9]{16}c$') { throw 'Generated corruption database name is invalid.' }

    # Require the existing Compose database to be healthy. This runner never
    # starts, stops or recreates the service; the CI job starts it explicitly.
    try {
        Invoke-ComposeDb @('sh', '-ec', 'exec pg_isready -U "$POSTGRES_USER"')
    } catch {
        throw 'The Docker Compose PostgreSQL service is not healthy. Start it with ./scripts/dev.ps1 db.'
    }
    if (!(Test-AcceptanceDatabaseExists $operatingDatabase)) {
        throw 'The normal StoreOS database is missing from the Compose server.'
    }
    if (Test-LoopbackPort $apiPort) {
        throw "Loopback port $apiPort is already in use; stop that service first."
    }

    New-Item -ItemType Directory -Path $runDirectory -Force | Out-Null
    Push-Location $serverDirectory
    try {
        if (!$SkipPackageResolution) {
            & $dartTool pub get --enforce-lockfile
            if ($LASTEXITCODE -ne 0) { throw 'Server package resolution failed.' }
        } elseif (!(Test-Path -LiteralPath '.dart_tool/package_config.json')) { throw 'Cached package configuration required.' }
    } finally { Pop-Location }

    $env:STOREOS_BACKUP_MANIFEST = $manifestPath
    $env:STOREOS_BACKUP_RESULT = $resultPath
    $env:STOREOS_BACKUP_SOURCE_DATABASE = $sourceDatabase
    $env:STOREOS_BACKUP_TARGET_DATABASE = $restoreDatabase
    $env:STOREOS_BACKUP_DB_HOST = $databaseHost
    $env:STOREOS_BACKUP_DB_PORT = "$databasePort"
    $env:STOREOS_BACKUP_DB_USER = $ownerUser
    $env:STOREOS_BACKUP_OWNER_PASSWORD_FILE = $ownerPasswordFile
    $env:STOREOS_BACKUP_API_PORT = "$apiPort"
    $env:STOREOS_DB_USER = $runtimeUser
    $env:STOREOS_DB_PASSWORD_FILE = $runtimePasswordFile

    $failedStep = 'create-source-database'
    New-AcceptanceSourceDatabase $sourceDatabase
    $steps.createSourceDatabase = $true

    $failedStep = 'prepare'
    Invoke-Fixture 'prepare'
    $steps.prepare = $true
    if (!(Test-Path -LiteralPath $manifestPath -PathType Leaf)) { throw 'The acceptance manifest was not written.' }
    if ($InjectFailureAfter -ceq 'prepare') { throw 'Injected failure after prepare.' }

    $failedStep = 'backup'
    & (Join-Path $repository 'infra/backup/Backup-StoreOS.ps1') -Database $sourceDatabase -BackupDirectory $runDirectory -DockerPath $dockerTool
    $backups = @(Get-ChildItem -LiteralPath $runDirectory -Filter 'storeos-*.sodb' -File)
    if ($backups.Count -ne 1) { throw 'Expected exactly one acceptance backup file.' }
    $backupPath = $backups[0].FullName
    $backupManifest = Get-Content -Raw -LiteralPath "$backupPath.json" | ConvertFrom-Json
    if ($backupManifest.sourceDatabase -cne $sourceDatabase) {
        throw 'The backup manifest does not name the acceptance source database.'
    }
    $steps.backup = $true
    if ($InjectFailureAfter -ceq 'backup') { throw 'Injected failure after backup.' }

    $failedStep = 'restore'
    & (Join-Path $repository 'infra/backup/Restore-StoreOS.ps1') -BackupPath $backupPath -TargetDatabase $restoreDatabase -DockerPath $dockerTool
    $steps.restore = $true
    if ($InjectFailureAfter -ceq 'restore') { throw 'Injected failure after restore.' }

    $failedStep = 'verify'
    Invoke-Fixture 'verify'
    if (!(Test-Path -LiteralPath $resultPath -PathType Leaf)) { throw 'The verification result is missing.' }
    $verify = Get-Content -Raw -LiteralPath $resultPath | ConvertFrom-Json
    if ($verify.sourcePreserved -ne $true -or $verify.restoredRuntimeConnectionRejected -ne $true) {
        throw 'Verification did not confirm source preservation and runtime fencing.'
    }
    $steps.verify = $true
    if ($InjectFailureAfter -ceq 'verify') { throw 'Injected failure after verify.' }

    $failedStep = 'corruption'
    $corruptPath = Join-Path $runDirectory 'corrupt.sodb'
    [IO.File]::Copy($backupPath, $corruptPath, $true)
    $corruptBytes = [IO.File]::ReadAllBytes($corruptPath)
    if ($corruptBytes.Length -le 68) { throw 'The acceptance backup is unexpectedly small.' }
    $corruptBytes[[int][Math]::Floor($corruptBytes.Length / 2)] = $corruptBytes[[int][Math]::Floor($corruptBytes.Length / 2)] -bxor 1
    [IO.File]::WriteAllBytes($corruptPath, $corruptBytes)
    $corruptManifest = Get-Content -Raw -LiteralPath "$backupPath.json" | ConvertFrom-Json
    $corruptManifest.encryptedFile = [IO.Path]::GetFileName($corruptPath)
    $corruptManifest.encryptedSha256 = (Get-FileHash -LiteralPath $corruptPath -Algorithm SHA256).Hash.ToLowerInvariant()
    [IO.File]::WriteAllText("$corruptPath.json", ($corruptManifest | ConvertTo-Json -Depth 3),
        [Text.UTF8Encoding]::new($false))
    try {
        & (Join-Path $repository 'infra/backup/Restore-StoreOS.ps1') -BackupPath $corruptPath -TargetDatabase $corruptDatabase -DockerPath $dockerTool
    } catch {
        $corruptRejected = $true
    }
    if (!$corruptRejected) { throw 'The tampered backup was restored successfully.' }
    $steps.corruptionRejected = $true
    $removeResult = Remove-AcceptanceDatabase $corruptDatabase $ownedDatabaseNames
    if ($removeResult -ne 'removed') { throw 'The corrupted restore target was not removed.' }
    $corruptTargetRemoved = $true
    if ($InjectFailureAfter -ceq 'corruption') { throw 'Injected failure after corruption.' }

    $failedStep = 'none'
    $runVerified = $true
} catch {
    $failure = $_
}

$finishedAtUtc = [DateTime]::UtcNow.ToString('o')

try {
    # Cleanup always runs, including after injected failures. Only this run's
    # strictly named databases are considered.
    foreach ($name in $ownedDatabaseNames) {
        try {
            $cleanup[$name] = Remove-AcceptanceDatabase $name $ownedDatabaseNames
        } catch {
            $cleanup[$name] = 'FAILED'
            if (!$cleanupFailure) { $cleanupFailure = $_ }
        }
    }
    try {
        $cleanup.operatingDatabasePresent = Test-AcceptanceDatabaseExists $operatingDatabase
        if (!$cleanup.operatingDatabasePresent) { throw 'The normal StoreOS database is missing after cleanup.' }
    } catch {
        $cleanup.operatingDatabasePresent = $false
        if (!$cleanupFailure) { $cleanupFailure = $_ }
    }
    try {
        $portFree = -not (Test-LoopbackPort $apiPort)
        $cleanup.acceptancePortFree = $portFree
        if (!$portFree) { throw "The acceptance API port $apiPort is still in use." }
    } catch {
        $cleanup.acceptancePortFree = $false
        if (!$cleanupFailure) { $cleanupFailure = $_ }
    }

    $report = [ordered]@{
        runId              = $runId
        startedAtUtc       = $startedAtUtc
        finishedAtUtc      = $finishedAtUtc
        result             = if ($failure -or $cleanupFailure) { 'failed' } else { 'pass' }
        failedStep         = $failedStep
        operatingDatabase  = $operatingDatabase
        sourceDatabase     = $sourceDatabase
        restoreDatabase    = $restoreDatabase
        steps              = $steps
        verification       = $verify
        corruption         = [ordered]@{ rejected = $corruptRejected; targetRemoved = $corruptTargetRemoved }
        cleanup            = $cleanup
    }
    [IO.File]::WriteAllText($reportPath, ($report | ConvertTo-Json -Depth 8),
        [Text.UTF8Encoding]::new($false))
    Assert-BackupAcceptanceReport -Path $reportPath -SensitiveValues $sensitiveValues.ToArray()
} catch {
    if (!$cleanupFailure) { $cleanupFailure = $_ }
    if (Test-Path -LiteralPath $reportPath -PathType Leaf) {
        Remove-Item -LiteralPath $reportPath -Force
    }
} finally {
    if ($failure -or $cleanupFailure) { Write-FixtureFailureDiagnostics }
    foreach ($name in @('fixture.json', 'verify-result.json')) {
        $path = Join-Path $runDirectory $name
        if (Test-Path -LiteralPath $path -PathType Leaf) { Remove-Item -LiteralPath $path -Force }
    }
    foreach ($pattern in @('storeos-*.sodb', 'storeos-*.sodb.json', 'corrupt.sodb', 'corrupt.sodb.json')) {
        foreach ($file in @(Get-ChildItem -LiteralPath $runDirectory -Filter $pattern -File -ErrorAction SilentlyContinue)) {
            Remove-Item -LiteralPath $file.FullName -Force
        }
    }
    foreach ($file in @(Get-ChildItem -LiteralPath $runDirectory -Filter 'fixture-*.log' -File -ErrorAction SilentlyContinue)) {
        Remove-Item -LiteralPath $file.FullName -Force
    }
    foreach ($name in $previousEnvironment.Keys) {
        [Environment]::SetEnvironmentVariable($name, $previousEnvironment[$name], 'Process')
    }
}

if ($failure) {
    Write-Error "Backup/restore acceptance failed at $failedStep. Report: $reportPath. $($failure.Exception.Message)" -ErrorAction Continue
    if ($cleanupFailure) { Write-Error "Cleanup also failed: $($cleanupFailure.Exception.Message)" -ErrorAction Continue }
    exit 1
}
if ($cleanupFailure) {
    Write-Error "Backup/restore acceptance verification failed or cleanup was incomplete. Report: $reportPath. $($cleanupFailure.Exception.Message)" -ErrorAction Continue
    exit 1
}
if (!$runVerified) {
    Write-Error 'Backup/restore acceptance did not complete all steps.' -ErrorAction Continue
    exit 1
}
Write-Host "Backup/restore acceptance passed. Sanitized report: $reportPath"
